export default {
    "static": {name:"antd-fc-static"},
    "text": {name:"antd-fc-text"},
    "textarea": {name:"antd-fc-textarea"},
    "date": {name:"antd-fc-date"},
    "date-range": {name:"antd-fc-date-range"},
    "date-local": {name:"antd-fc-date"},
    "date-full": {name:"antd-fc-date"},
    "select": {name:"antd-fc-select",async:false},
    "buttonlist": {name:"antd-fc-buttonlist"},
    "number-range":{name:"antd-fc-number-range"},
    "number":{name:"antd-fc-number"},
    "uploadfile":{name:"antd-fc-uploadfile"},
    "tree":{name:"antd-fc-tree"},
    "autocomplete":{name:"antd-fc-autocomplete"},
    "selecttable":{name:"antd-fc-autocomplete"},
    "radiolist":{name:"antd-fc-radiolist"},
    "checkboxlist":{name:"antd-fc-checkboxlist"},
    "switcher":{name:"antd-fc-switcher"}
}